### ISSUE TITLE
Cannot connect (library/sections is 401)

### ISSUE THREAD

**Issue by michaelcadilhac** [Aanok/pmcli#1]
Hi there!  Looks like a great project you have here!—although I fail completely to start it :-)

After configuration, I obtain the following error:
```
Plex Media CLIent v0.1
Connecting to Plex Server...
[!!!] Network error on API request https://url:port/library/sections:
starttls: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:unable to get local issuer certificate
```

I can certainly access the server with Chrome, and the SSL cert is valid and signed by Let's Encrypt. However, `library/sections` just give a 401 Unauthorized in Chrome, so that may be the problem.  Should I allow some kind of additional access somewhere?

PS: I had to manually install lua-socket; missing dependency?

**Comment by Aanok** [comment]
Haha, thanks, let's see. From what I can tell, the error comes from the client being unable to verify the certificate with the issuing authority which, in theory, should be handled automatically by lua-http (or rather luaossl). But I'm looking into this.

Meanwhile, maybe you're serving Plex under a reverse proxy? If you do, could you post your config?

In any case, you're likely getting 401 on the browser because you need to either set an `X-Plex-Token: ...` header or request `library/sections?X-Plex-Token=...` if the request's source IP hasn't been authorized in Plex under `Settings>Server>Network>List of IP addresses and networks that are allowed without auth` (show advanced).
Could you try that? You should find a working token in `$HOME/.config/pmcli_config`.

And thanks for the luasocket spot, that's been fixed :)

**Comment by michaelcadilhac** [comment]
Thanks for the swift response.  I'm not using a reverse proxy.  Using the token as you described does work indeed, I do get the XML tree of directories.  Do let me know if I can provide more details!

**Comment by Aanok** [comment]
Would you mind reporting the output of `echo | openssl s_client -connect address:port`? Without prefixing the address with https://.

**Comment by michaelcadilhac** [comment]
Tell you what, cause I'm a bit confused.  My server is `cadilhac.name` with the default port.  What I don't get is that openssl reports that the SSL certificate is Plex's, and that makes, say, `wget` fail.  But Chrome reports that it's my custom certificate, as I've configured in Plex.  Not sure what protocols are at play here.

**Comment by Aanok** [comment]
For the moment, as a dreadful hotfix I've made it so you can add `verify_server_certificates = false` in `pmcli_config` to completely skip any certificate validation. You'll forego identity verification, but you'll still have encryption.

For something cleaner, I'm still not sure and will need to investigate more. It looks like Plex serves different certificates for different occasions.

Curl sees a post-processed version of the custom PKCS12 certificate built concatenating Plex's own certificate and chain of trust to it: you can see this if you run `curl --trace - https://cadilhac.name:32400 --output /dev/null` . wget and lua-ossl seem to see this one too and they all consequently throw a fit.

In browser, as you say, you get your own and it's fine (and reasonable).

Openssl s_client sees only the Plex certificate, which is also fine (but unreasonable).

**Comment by michaelcadilhac** [comment]
Frankly, I did not even know this was possible.  Is Plex to be blamed here?

**Comment by Aanok** [comment]
Mind trying again? I think that it's working now that you've renewed your certificate.

**Comment by michaelcadilhac** [comment]
B… but how‽  That's sorcery.  Somehow, curl & the rest are happy, and openssl still returns the Plex one.  Oh my.  Well, let's close our eyes on that one, and pretend it never happened.  Thanks for your help and this nice project—which hopefully in the future will be controllable from the web interface as a player ;-)  Cheers!

**Comment by Aanok** [comment]
Hahaha, sorcery indeed. You didn't change anything in your configuration beyond renewing the certificate?

Also, I've been told openssl's behavior is as expected due to Server Name Indication. try running `echo | openssl s_client -servername cadilhac.name -connect cadilhac.name:32400` and you'll see your certificate show up.
